name: roboshop
services: 
  mongodb:
    build: ./mongodb
    image: 225834/mongodb:v1
    container_name: mongodb
  catalogue:
    build: ./catalogue
    image: 225834/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    image: 225834/frontend:v1
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - catalogue
      - user
      - cart
  redis:
    image: redis:7
    container_name: redis
  user:
    build: ./user
    image: 225834/user:v1
    container_name: user
    environment:
      MONGO: true
      REDIS_URL: 'redis://redis:6379'
      MONGO_URL: "mongodb://mongodb:27017/users"
    depends_on:
      mongodb:
       condition: service_healthy
      redis:
       condition: service_healthy
  cart:
    build: ./cart
    image: 225834/cart:v1
    container_name: cart
    environment:
      REDIS_HOST: "redis"
      CATALOGUE_HOST: "catalogue"
      CATALOGUE_PORT: "8080"
    depends_on:
      redis:
        condition: service_healthy
      catalogue:
        condition: service_healthy
  mysql:
    build: ./mysql
    image: 225834/mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "RoboShop@1"
  
networks:
  default:
    name: roboshop
    driver: bridge
    external: false
      
